from crp import CRP
from bah import BAH
from anticor import Anticor
from corn import CORN
from bcrp import BCRP
from cwmr import CWMR
from olmar import OLMAR
from pamr import PAMR
from rmr import RMR
from up import UP
from wmamr import WMAMR
from ons import ONS
from kelly import Kelly
from up import UP
from eg import EG
from bnn import BNN
